name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- traitsui==7.1.0
- matplotlib-base
- numpy
- scipy
- sympy
- k3d
- ipywidgets
- ipympl
#- vtk
#- mayavi
- pip
- pip:
  - -e .
  - bmcs_utils
